### PR TITLE
feature: add enum classes

### PR DESCRIPTION
**Pull request by krzhld**
Enum classes (Delivery, Food, Song and WebWork) were added.

### CODE REVIEW

**Review by Bazalii — CHANGES_REQUESTED** [review]
Realisation is nice, but please add a newline at the end of every file

**Comment by krzhld** [comment]
Newlines were added

**Review by Bazalii — APPROVED** [review]
Everything is nice. I want to mention that it is better to use 'feature' instead of 'docs' for code files. Don't forget to add list of solved issues or limk issues with pull request manually.

**Comment by Ferrociraptus** [comment]
In the future these enums will have to move to files where it is will be used (for example files with abstraction classes of states).
And now you should link issues that you want to close by this request (and for best practice write issues list in merge request description).

**Review by Ferrociraptus — CHANGES_REQUESTED** [review]
In the future these enums will have to move to files where it is will be used (for example files with abstraction classes of states).
And now you should link issues that you want to close by this request (and for best practice write issues list in merge request description).

**Pull request closed without merging**
