### PR TITLE
feature: add abstract class "StudyCourseState" and interface "TimerObserver" for it

### PR DESCRIPTION
**Pull request by krzhld**
Added interface TimerObserver and abstract class StudyCourseState
- TimerObserver includes itself two empty functions
- Abstract class StudyCourseState inherites from the interface. There are val integer property "price", empty function buyNextCourse, which can change object "student" of class "Player". Functions from interface were overrided, but they are still empty

### CODE REVIEW

**Review by Bazalii — CHANGES_REQUESTED** [review]
Also newlines. I wrote about that in .editorconfig. Also don't forget to use Draft if you don't want me to review your files and add closes: Issue in pull request

**Comment by krzhld** [comment]
Newlines were added

**Review by Bazalii — COMMENTED** [review]
For this moment everything is fine but I won't approve this pull request without method's bodies. You cannot write their realisations because we do not have all the files ready now but when they are ready you will have to add normal realisation...

**Comment by Ferrociraptus** [comment]
> For this moment everything is fine but I won't approve this pull request without method's bodies. You cannot write their realisations because we do not have all the files ready now but when they are ready you will have to add normal realisation...

@Bazalii, this class is only abstraction, why you want to see their body implementation now? Implementation should be in child classes. And don't forget that this request named as "add abstract class ...". It should be accepted if @krzhld add issues list and issue, which one he wants to close would be with same task.

**Comment by Ferrociraptus** [comment]
@krzhld, you should link issues that you want to close by this request (and for best practice write issues list in merge request description).

**Pull request closed without merging**
