### PR TITLE
Many changes in UML files: names, properties, spelling mistakes

### PR DESCRIPTION
**Pull request by Bazalii**
### Improvements in Player_class:
- change the style for variables from lowerCamelStyle to our_chosen_style
- replace minus in fields of abstract classes with #
- remove fileds guitar, bicycle, computer and add the field items: Bag
- add two new data classes(Bag and Courses) inside player
- add two new methods buyNextGuitarCourse() and buyNextComputerCourse()
- Change type for available Lists from String to KClass<*>
- prise -> price
- reduse -> reduce
- sechool -> school
- avaliable -> available
- difficult -> difficulty
- perfomans -> performance
- komputer -> computer
- checkLoosing -> checkDefeat
- knownSongsList -> deleted
- knownKomputerWorks-> deleted
- is_smth_available -> isAvailable
- canPlaySong -> isAvailable
- For variables: webWork -> web_task
- For Enum: WebWork -> WebTask
- deliverType -> delivery_type
- UsualUSSR_guitarState -> UssrGuitarState
- MusicianObservatoryCourseState -> MusicalObservatoryCourseState
- MusicianSchoolCourseState -> MusicalSchoolCourseState

### Improvements in Game_class:
- change the style for variables from lowerCamelStyle to our_chosen_style
- replace minus in fields of abstract classes with plus
- Dellay -> Delay
- dependenses -> dependencies
- GameDifficultState -> GameDifficultyState
- checkLoosing -> checkDefeat

### Reasons for that:
- more logical structure of code
- more understandable names
- more accurate names in terms of the construction of the English language (English structure, correct meanings etc.)
- correction of spelling mistakes

Closes: #23

### CODE REVIEW

**Review by Ferrociraptus — CHANGES_REQUESTED** [review]
If you change fields in the game abstract class, you should change the access type into child classes too.

You changed field access type in PlayerState as protected thus you can't take these values from the Player class. I think it should be public or an addiction method should be added.

Do you sure that prices fields access type should be protected, not private?

If you add some inner classes like a bag, other methods to take thing fields in Player classes should be deprecated or removed (for example owner field in ComputerState).

If you want to simplify methods names, you can rename canPlay() in GuitarCourseState on isAvailable().

If you change methods access type in abstract classes, you should select this access type in their children's classes. (GameDifficultState)

And in the end, if you change the doc you should update add renders of this document (.png .svg e.t.c.)

**Comment by Bazalii** [comment]
> If you change fields in the game abstract class, you should change the access type into child classes too.
> 
> You changed field access type in PlayerState as protected thus you can't take these values from the Player class. I think it should be public or an addiction method should be added.
> 
> Do you sure that prices fields access type should be protected, not private?
> 
> If you add some inner classes like a bag, other methods to take thing fields in Player classes should be deprecated or removed (for example owner field in ComputerState).
> 
> If you want to simplify methods names, you can rename canPlay() in GuitarCourseState on isAvailable().
> 
> If you change methods access type in abstract classes, you should select this access type in their children's classes. (GameDifficultState)
> 
> And in the end, if you change the doc you should update add renders of this document (.png .svg e.t.c.)

First of all, please, if you want someone to do several things **use a numbered list** because it will be mush easier for person and for you to chat about particular questions. it is difficult to concentrate on questions without numbers(bullet points). It will be also easier to highlight what is done our should be discussed, like:

1.  Fixed
2. I don't think it is the best solution here
3. Smth else..

So, now I'll move to your points:

1. FIxed
2.  Wait a minute.. In your version of UML file they were all private. So. this question is for you. If they have to be public or have access, I'll change that
3. We have already discussed that. We cannot make these fields private in abstract class, we can just remove them and initialize in children. I think that it is better just to make all fields protected, because it's more beautiful sollution and there is no reason in turning them into private in our case or am I mistaken? 
4. I didn't know that owner is for taking things out of player. Please point out, which fields and methods instead of owner should be deleted. I also want to mention that there was another sollution for 'bag' problem, we could just have 'a link'(owner) to our player object in all states and change state using Player's method 'changeState', it would be better solution if we could buy normal_bicycle after NullBicycle, for example, but our solution is better.
5. Fixed
6. Fixed. Are there any places where I forgot about that?
7. Of course, I'll do that and I remember about that but as a last commit after all changes will be made because I don't want to render every time six files...
8. Also I found some more mistakes in names of classes

**Review by Ferrociraptus — APPROVED** [review]
In the future, achievements implementation architecture should be added to these files. 
But now it looks fine.

**Comment by Ferrociraptus** [comment]
Please, after approval from the second person, add new versions of image files.

**Comment by Bazalii** [comment]
> In the future, achievements implementation architecture should be added to these files.
> But now it looks fine.

Yep. Kirill thinks about this implementation and I told him that it would be better to reflect it using UML diagrams

**Comment by Endray952** [comment]
Why don't we have methods that reduce percentage like we have with add methods? For example, PlayerState contains fields that reduce percentage of characteristics.

**Review by Endray952 — COMMENTED** [review]
Why don't we have methods that reduce percentage like we have with add methods? For example, PlayerState contains fields that reduce percentage of characteristics.

**Review by Endray952 — CHANGES_REQUESTED** [review]
1) Why don't we have methods that reduce percentage like we have with add methods? For example, PlayerState contains fields that reduce percentage of characteristics.
2) I think, fields price and values for states of player should be public with private setter. It's better in Kotlin

**Comment by Bazalii** [comment]
> 1. Why don't we have methods that reduce percentage like we have with add methods? For example, PlayerState contains fields that reduce percentage of characteristics.
> 2. I think, fields price and values for states of player should be public with private setter. It's better in Kotlin

1. We discussed that yesterday. We will check it carefully later using the main story of our game. If it is needed, we will add them in the future.
2. Yes, in reality we will do so, but UML diagrams show the structure abstractly not using particular programming language. For example, there are no static methods in kotlin and Game will be actually an "object" but if we wrote our program using cpp, we would have real static methods and real private or protected prices with setter and/or getter. Personally I think that is is not convenient to write abstractly because we have private fields in UML but in reality these fields will be public with private setter, we have static methods in UML but we won't have them in reality - only object, we also have private fields in inner classes of Player but they will be also public with private setter and getter. All that is kinda cringe and not convenient at all....

**Review by Endray952 — DISMISSED** [review]

**Review by Ferrociraptus — APPROVED** [review]
All are fine.

**Review by Endray952 — APPROVED** [review]

**Pull request merged**
